##[[
  cflags '-target x86_64-elf'
  cflags '-Wall -Wextra -O2 -pipe'
  cflags '-ffreestanding'
  cflags '-nostdlib'
  cflags '-fno-stack-protector'
  cflags '-fno-pic'
  cflags '-fpie'
  cflags '-mno-red-zone'
  ldflags '-Wl,-Tsys/link/x86_64.ld'
  ldflags '-Wl,-zmax-page-size=0x1000'
  ldflags '-Wl,-static'
  ldflags '-Wl,-pie'
  ldflags '-Wl,--no-dynamic-linker'
  ldflags '-Wl,-ztext'
  pragmas.nochecks = true
  pragmas.nogc = true
]]

require "os.pink"
